### PR TITLE
Accept pure strings as exception tags.

### PR DESCRIPTION
**Pull request by ammachado**

### CODE REVIEW

**Comment by JoshuaColeman** [comment]
@ammachado These changes look valuable to me! I was wondering why some things that were logged as exceptions were not showing up in RayGun when I saw them in the logfile. I'm not an administrator but these changes have my vote.

**Comment by CmdrKeen** [comment]
Looks great folks. @dwnz will take a peek and look to get this out. Really appreciate the addition.

**Comment by ammachado** [comment]
This package will be published to nuget?

**Comment by CmdrKeen** [comment]
We should get it on there. There is already a Raygun.Nlog on there, but it's maintained by an independent developer, not us. @dwnz will take a look at supporting it ourselves in there 👍

**Comment by JoshuaColeman** [comment]
@chekkan is the owner of the existing NLog.Raygun package. I coincidentally reached out to him a few days ago and he sounds open to having someone else manage it. I can't imagine anyone better than Mindscape :+1:

**Comment by CmdrKeen** [comment]
Ah cool, that would be best. Thanks for the details @JoshuaColeman :+1:

**Comment by dwnz** [comment]
PR looks good! Will merge in now.

Will also have a look at getting it into Nuget/taking over maintaining the package :)

**Comment by chekkan** [comment]
@CmdrKeen let me know how to transfer the ownership of the nuget package.

**Pull request merged**
