### PR TITLE
NetStandard + VS2017

### PR DESCRIPTION
**Pull request by snakefoot**
Now it is easier to create the nuget-package:

`dotnet pack src\NLog.Raygun --configuration Release --include-symbols`

Funny that it is not possible to provide UserInfo when calling `SendInBackground` with `Mindscape.Raygun4Net.AspNetCore`

### CODE REVIEW

**Comment by snakefoot** [comment]
Would it make sense to update NLog and Mindscape.Raygun4Net for the net45-build ?

NLog ver. 4.0.1 + Mindscape.Raygun4Net ver. 5.5.0 ? (Would remove the need for bindingRedirect for NLog)

**Comment by QuantumNightmare** [comment]
Thanks for the PR, I've added a ticket for us to look into this in a future sprint.

**Comment by snakefoot** [comment]
@QuantumNightmare So can this be merged, so an official Nuget-package can be created? And what about my suggestion of updating dependencies?

**Comment by QuantumNightmare** [comment]
Hi @snakefoot,

We've looked through this now. Only change to the PR we can see would be to change the company in the csproj from MindscapeHQ to Raygun.

Around dependencies, updating to the latest Raygun4Net would be good, but feel that NLog should be left as is with the binding redirect in order to avoid forcing people to upgrade to the latest NLog.

One thing to keep in mind is that we are currently working on building a Raygun4Net assembly that targets NetStandard 2.0 which may be a better dependency here than Raygun4Net.AspNetCore that you've added in this PR - ASPNet should not be needed here - let us know your thoughts on this.

Let us know if you'd like us to merge this PR first and switch to Raygun4Net NETStandard 2.0 in a separate PR, or if you're fine with waiting to use that in this PR. It's currently under development, expected to be done within 2 weeks if it doesn't get de-prioritized.

**Comment by snakefoot** [comment]
Would prefer to update to NLog 4.0 and generate the breaking change, since the nuget-package being released is a major version change. And binding redirects are cumbersome (Last nuget package release was 3 years ago, and most people have avoided it because of all its weird dependencies)

I think NLog.Raygun should move forward with Raygun4Net.AspNetCore until something non-beta comes up.

Will fix the company name for you.

**Comment by snakefoot** [comment]
@QuantumNightmare Fixed company name and updated to NLog 4.0 (Still 3 years old, so not dangerously bleeding edge)

When you have a non-beta NetStandard-Client, then someone can make a PR to update the nuget-package (Should be trivial).

**Comment by QuantumNightmare** [comment]
Thanks, we're happy with those changes. I'll merge this now and we'll look at releasing an official NuGet package.

**Comment by snakefoot** [comment]
@QuantumNightmare Possible to get an official Nuget-package?

P.S. Can see https://www.nuget.org/packages/Mindscape.Raygun4Net.NetCore/ is out. But it also fails to support custom `RaygunIdentifierMessage`

**Comment by QuantumNightmare** [comment]
@snakefoot NuGet package should be coming out the coming week, we were just waiting for replies from a couple of people around some final details for the release which we have now received.

Due to your contributions, did you want your name to be included as an author in the code or/and NuGet package?

I'll follow up regarding the RaygunIdentifierMessage in Raygun4Net.NetCore

**Comment by snakefoot** [comment]
You don't need to add me as author. Looking forward to a release :)

**Comment by QuantumNightmare** [comment]
@snakefoot NLog.Raygun v1.0.0 has now been released on NuGet. We've tested it out, but let us know if you spot anything amiss. Thanks for your help pushing this forward.

**Comment by snakefoot** [comment]
@QuantumNightmare Thank you for the release :). Looks good: https://www.nuget.org/packages/NLog.Raygun/

**Pull request merged**
