### PR TITLE
Updated to Raygun ver. 7.1  and replaced net5 with net6

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
Ready for review @mduncan26 + @phillip-haydon

**Comment by phillip-haydon** [comment]
Thank you @snakefoot - I'll give it a test today and publish a pre-release to nuget if I don't run into any issues.

**Comment by phillip-haydon** [comment]
https://www.nuget.org/packages/NLog.Raygun/7.1.0-pre-1

I've published a pre-release, I've tested it myself and it's all good, would you mind double checking it before I publish a release of it.

**Comment by snakefoot** [comment]
Thanks NLog.Raygun also looks good to me.

A little unrelated but strong-version looks funny for https://www.nuget.org/packages/Mindscape.Raygun4Net/ 

image

Where https://www.nuget.org/packages/Mindscape.Raygun4Net.AspNetCore/ is reports a more correct version:

image

Not really related to NLog.Raygun-package, which is ok (without strong-version)

**Review by phillip-haydon — APPROVED** [review]
:+1: thanks for picking this up. I'll get a full release out Monday morning, just a bit busy today.

**Comment by phillip-haydon** [comment]
Will also take a look at the SN thing too, thanks for pointing that out.

**Comment by phillip-haydon** [comment]
Sorry for the delay, I published 7.1.0 to nuget.

**Comment by snakefoot** [comment]
Awesome. Thank you

**Pull request merged**
