### PR TITLE
Updated to Raygun ver. 10.1 with reduced dependencies

### PR DESCRIPTION
**Pull request by snakefoot**
Preview of README.md - https://github.com/snakefoot/NLog.Raygun

### CODE REVIEW

**Comment by snakefoot** [comment]
Maybe wait for https://github.com/MindscapeHQ/raygun4net/pull/503 to be merged and released, so more unnecessary dependencies are removed.

**Comment by snakefoot** [comment]
@phillip-haydon Ready for review

**Comment by phillip-haydon** [comment]
Hello @snakefoot sorry for the delay, v10 of Raygun4Net is out with a bunch of fixes I was waiting for to ship with NLog, do you want to update the PR and I can merge get this released, if not then I can do it this week.

**Comment by snakefoot** [comment]
Looks like there is API-bug in the `RaygunClient`:
```
    public RaygunClient(RaygunSettings settings, HttpClient? httpClient = null, IRaygunUserProvider? userProvider = null)
        : base(settings, httpClient, userProvider)
    {
    }

    public RaygunClient(RaygunSettings settings, IRaygunUserProvider? userProvider = null)
        : base(settings, null, userProvider)
    {
    }
```
You cannot use default-parameters for both constructors.

**Comment by snakefoot** [comment]
Have also created https://github.com/MindscapeHQ/raygun4net/pull/524 to improve BreadCrumb performance in Raygun ver. 10

**Comment by phillip-haydon** [comment]
> Looks like there is API-bug in the `RaygunClient`:
> 
> ```
>     public RaygunClient(RaygunSettings settings, HttpClient? httpClient = null, IRaygunUserProvider? userProvider = null)
>         : base(settings, httpClient, userProvider)
>     {
>     }
> 
>     public RaygunClient(RaygunSettings settings, IRaygunUserProvider? userProvider = null)
>         : base(settings, null, userProvider)
>     {
>     }
> ```
> 
> You cannot use default-parameters for both constructors.

Hmmm this was suggested by Rider. Is it blocking? I can rejig the ctors later.

**Comment by snakefoot** [comment]
> > You cannot use default-parameters for both constructors.
> 
> Hmmm this was suggested by Rider. Is it blocking? I can rejig the ctors later.

The following code will not compile:
```
var client = new RaygunClient(settings); // unable to guess the constructor
```
So one have to be explicit, and provide all parameters. By default one should avoid default-values in public API, when having multiple methods/constructors.

**Comment by phillip-haydon** [comment]
I have release 10.1.1 which includes the ctor re-working, so this should be ok now.

**Comment by snakefoot** [comment]
Thanks for the heads up. I have now updated to ver. 10.1.1 and it looks good.

**Comment by phillip-haydon** [comment]
@ProRedCat would you mind double checking the breadcrumb usage in here.

**Review by phillip-haydon — APPROVED** [review]
:+1:

**Comment by phillip-haydon** [comment]
Will try get a release done asap for this, thank you.

**Comment by snakefoot** [comment]
Sounds awesome. Thank you for accepting the pull-request.

**Comment by phillip-haydon** [comment]
I've pushed out v8
https://www.nuget.org/packages/NLog.Raygun/8.0.0

Please let me know if there's any issues.

**Pull request merged**
