### PR TITLE
Added support for UserIdentityInfo for NetCore, and context-properties

### PR DESCRIPTION
**Pull request by snakefoot**
Now possible to do this:

```xml
	<target name="RayGunTarget" type="RayGun" ApiKey="">
		<contextproperty name="RenderedLogMessage" layout="${message}" />
		<contextproperty name="LogMessageTemplate" layout="${message:raw=true}" />
		<contextproperty name="Logger" layout="${logger}" />
		<contextproperty name="ThreadId" layout="${threadid}" />
        </target>
```

### CODE REVIEW

**Comment by snakefoot** [comment]
@QuantumNightmare Ready for review

**Comment by snakefoot** [comment]
@mduncan26 Ready for review.

**Comment by mduncan26** [comment]
Hi @snakefoot 

Thank you for the PR, I will raise this with the team and we will schedule a time to review this work. I will be in touch again once  I have confirmed a time in which this will be reviewed. If you wish to update your other open PR (https://github.com/MindscapeHQ/NLog.Raygun/pull/6) we can look to review this one as well.

Regards,
Mitchell.

**Comment by snakefoot** [comment]
Think this should be merged first because of the included editorconfig. Then I will rebase my other PR to add support breadcrumbs.

**Comment by mduncan26** [comment]
Hi @snakefoot 

We have been able to review the PR and found no issues. We will look to publish the changes to NuGet soon. Thank you for taking the time.

Regards,
Mitchell.

**Comment by snakefoot** [comment]
Thank you for the merge. Have now rebased #6 and resolved conflicts.

**Comment by mduncan26** [comment]
Hi @snakefoot 

These changes along with the update to include breadcrumbs is now available through NuGet.

https://www.nuget.org/packages/NLog.Raygun/2.0.0

Please note we have done a little bit of cleanup for the SDK and updated the use of the Raygun name to be the correct spelling. You will need to make a couple of changes in order for this new version to work within your current integration when updating.

Thank you,
Mitchell.

**Comment by snakefoot** [comment]
Thank you for the release. The change in letter-casing of the class-name will not affect loading from `NLog.config`. Only when configuring RaygunTarget directly from code.

**Pull request merged**
