### PR TITLE
Added .NET5 as a compilation target

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
@mduncan26 + @samuel-holt Ready for review

**Comment by snakefoot** [comment]
Polite poke @mduncan26 + @Deacon-McIntyre + @samuel-holt

**Comment by Olwiba** [comment]
👋 Hey @snakefoot - just letting you know that this is on the radar & have a ticket for this to be actioned. Hoping to get to this soon but just need to work this around current workstreams

**Review by Callum-McKay — APPROVED** [review]
🚀 Thanks for the changes

**Comment by snakefoot** [comment]
Thank you for releasing [NLog.Raygun ver. 2.0.1](https://www.nuget.org/packages/NLog.Raygun)

**Pull request merged**
