### PR TITLE
Removed System.Web.Mvc dependency and included userCustomData

### PR DESCRIPTION
**Pull request by snakefoot**
Better support for structured logging

### CODE REVIEW

**Comment by snakefoot** [comment]
Looks like the `RaygunException` was the workaround until Raygun included breadcrumbs with ver. 5.5.0:

https://raygun.com/blog/breadcrumbs/

**Comment by snakefoot** [comment]
The `RaygunBreadcrumbTarget` should be included as a separate target for this nuget-package (other PR):

https://gist.github.com/j5alive/2d24b40fa3e0b101b5f6d91b4af4aa5d

**Comment by snakefoot** [comment]
@QuantumNightmare or @j5alive Any chance of this being approved and merged?

Planning an extra PR that converts the project to VS2017 and adds NetCore-support.

**Comment by CmdrKeen** [comment]
Hi Rolf,

Just a quick note that our New Zealand office closes for a couple of weeks for the Christmas vacation time down here (too damn hot to work anyway!) so Jason & Jeremy will be available to take a look at this early next week. 

Kind regards,

John-Daniel Trask

**Comment by snakefoot** [comment]
@QuantumNightmare Have updated the code-layout so the Github comparison is easier for the eye (changed indent from 4 spaces back to 2 spaces).

**Comment by darayman** [comment]
I am liking everything about this PR, great job @snakefoot.  I was just looking again to see if I could used the official NLog RayGun target and was looking through the source and didnt like fact that I need to pass in parameters even though the client automatically grab them from RaygunSettings section from the web/app.config and the dependency to System.Web.Mvc. So this resolves that and then some.

**Comment by snakefoot** [comment]
Also planning to create a new PR with support for NetCore, but first I need to get rid of the non-standard stuff like System.Web.Mvc (reason for this PR). But it seems they really know how to celebrate christmas in New Zealand :)

**Comment by QuantumNightmare** [comment]
@snakefoot Thanks for the PR. We'll look at merging this for a future release of Raygun4Net. We'll try prioritize this to make way for your next PR.

**Comment by snakefoot** [comment]
@QuantumNightmare Sounds great, though not sure why it is dependent on a future release of Raygun4Net. This is a seperate nuget-package called NLog.Raygun

**Comment by QuantumNightmare** [comment]
Yes sorry - NLog.Raygun :)

**Comment by snakefoot** [comment]
@QuantumNightmare Polite ping. Would like to add NetCore support

**Comment by snakefoot** [comment]
@mduncan26 & @QuantumNightmare  Polite ping. Would like to add NetCore support after this has been approved

**Comment by QuantumNightmare** [comment]
@snakefoot, apologies for the delay, I've found some time to look into this now. It all looks good except for what appears to be a breaking change which I figured I'd raise first before merging this. The UseIdentityNameAsUserId field has been removed from the config. For anyone using NLog.Raygun from this repo and does already have the UseIdentityNameAsUserId field in their configs, updating to use the code in this PR seems like it will cause it to stop working.

To see this yourself locally, on this branch, add the UseIdentityNameAsUserId back into the config of the test app. Then run the app and you'll find that the test exception does not make it to Raygun. Putting a break point in the Write method, you should find that when the UseIdentityNameAsUserId is present in the config, the break point doesn't get hit, but when the UseIdentityNameAsUserId is removed it does get hit and works as expected.

I'm not toooo fused about this, mainly because we have not yet published this NLog.Raygun to NuGet ourselves, so in a way, when we do, it will be the first version. (NLog.Raygun on NuGet was published by someone else - even then, we could always do a major version bump). But if possible/easy, I feel it would be best to avoid this breaking change to make it as convenient as possible for existing users.

It would be great to get any feedback you have about this, or let me know if I've misunderstood how NLog configs work that would make this not a breaking change.

**Comment by snakefoot** [comment]
@QuantumNightmare Apparently that is the behavior of NLog. If a single target is configured wrong, then no logging is performed.

I have re-added the property and marked it as obsolete.

**Comment by QuantumNightmare** [comment]
Thanks for making that change, I'll merge that in now.

**Comment by snakefoot** [comment]
@QuantumNightmare Thank you. Have now created #4 that makes it easier to create nuget-packages.

**Comment by snakefoot** [comment]
@darayman NLog.Raygun ver. 1.0 released https://www.nuget.org/packages/NLog.Raygun/

**Pull request merged**
