### PR TITLE
Updated dependencies and fixed breaking change

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
@mduncan26 Possible to have this merged and released? Allows NLog to work with:

https://www.nuget.org/packages/Mindscape.Raygun4Net.AspNetCore/6.1.0

**Comment by mduncan26** [comment]
Hi @snakefoot ,

Thank you for taking the time to make these changes. At this point in time we don't want to tie those who are not using the .NET Framework version 4.5 to the Raygun ASP.NET Core provider. 

We believe the better solution would be to release a separate package dedicated to ASP.NET Core in the same way the NLog packages do here: https://www.nuget.org/packages/NLog.Web.AspNetCore/.

We currently do not have this included on our product roadmap. I will make a note of this to pass onto our product manager. In the meantime you can gather community support by making a feature request in our forum (https://raygun.com/forums). This can help us prioritise the highly 
features for our product roadmap.

Thank you,
Mitchell.

**Comment by snakefoot** [comment]
@mduncan26 Can you explain how this change stops Net45 users from using Raygun?

This PR merely updates NLog.Raygun to use latest dependencies (Still supports Net45 + NetCore). Allowing all users to use latest version of Raygun-components.

**Comment by mduncan26** [comment]
Sorry I apologise @snakefoot. You are correct, I misread the changes. I will pass this on to the team for the changes to be tested. 

We can then look to merge this in once done.

Thank you.

**Comment by snakefoot** [comment]
Hope the testing has been successful, so a release can be made. If not then please tell :)

**Comment by mduncan26** [comment]
Hi @snakefoot, 

The work to review this PR was not brought into our current development sprint. It is at the top of the list of work to be picked up in our next sprint cycle. This next sprint will begin mid next week. I will let you know if this work is picked up earlier. Sorry for the delay.

Thank you,
Mitchell.

**Comment by snakefoot** [comment]
@mduncan26 Any progress on sprinting to the finish line?

**Comment by mduncan26** [comment]
Hi @snakefoot, we are currently reviewing the PR and will be in touch over the next day. Thank you.

**Comment by mduncan26** [comment]
Hi @snakefoot, we have tested the changes and found no issues. We will accept the PR. Thank you for taking the time and for your patience. We will release a new NuGet package shortly.

**Comment by snakefoot** [comment]
@mduncan26 Thank you for the merge. Lookup forward to an updated nuget-package:

https://www.nuget.org/packages/NLog.Raygun

Btw. Any chance you also could merge #8 since its a valid update of the docs.

**Comment by mduncan26** [comment]
@snakefoot The update is now available here: https://www.nuget.org/packages/NLog.Raygun/1.1.0.

I have merged in the other PR as well.

**Comment by snakefoot** [comment]
Excellent. Thank you for the help :)

**Pull request merged**
